# Generated by Django 6.0.3 on 2026-09-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_aluno_data_nascimento_remove_aluno_email_and_more'),
        ('exercicios', '0002_remove_exercicio_descricao'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='treinoexercicio',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treino_exercicios', to='exercicios.exercicio'),
        ),
        migrations.AlterField(
            model_name='treinoexercicio',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treino_exercicios', to='treinos.treino'),
        ),
        migrations.CreateModel(
            name='AlunoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_treinos', to='alunos.aluno')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_treinos', to='treinos.treino')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aluno', 'treino'), name='aluno_treino_unico')],
            },
        ),
    ]
